# Generated by Django 5.0.7 on 2024-07-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
